// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_zpj8H3mxSiP1KElYjwIluZHQmpqnFtE',
    appId: '1:812253569425:web:dc955030cc66afa833ba30',
    messagingSenderId: '812253569425',
    projectId: 'uts-1123150059',
    authDomain: 'uts-1123150059.firebaseapp.com',
    storageBucket: 'uts-1123150059.firebasestorage.app',
    measurementId: 'G-KZDE6MHMQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdJyyJWLiy0zck0DkWY8Gs-8-6I5HLb8c',
    appId: '1:812253569425:android:905cbf7587f9f1c133ba30',
    messagingSenderId: '812253569425',
    projectId: 'uts-1123150059',
    storageBucket: 'uts-1123150059.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGZPM0ErQw8CXyVwHKNFEVg5homK9AfFU',
    appId: '1:812253569425:ios:7cf7f818190c874933ba30',
    messagingSenderId: '812253569425',
    projectId: 'uts-1123150059',
    storageBucket: 'uts-1123150059.firebasestorage.app',
    iosClientId: '812253569425-0gchsbi5qnv9sldoua7atcr5os2nsefe.apps.googleusercontent.com',
    iosBundleId: 'com.example.uts1123150059',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGZPM0ErQw8CXyVwHKNFEVg5homK9AfFU',
    appId: '1:812253569425:ios:7cf7f818190c874933ba30',
    messagingSenderId: '812253569425',
    projectId: 'uts-1123150059',
    storageBucket: 'uts-1123150059.firebasestorage.app',
    iosClientId: '812253569425-0gchsbi5qnv9sldoua7atcr5os2nsefe.apps.googleusercontent.com',
    iosBundleId: 'com.example.uts1123150059',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_zpj8H3mxSiP1KElYjwIluZHQmpqnFtE',
    appId: '1:812253569425:web:2e9df600407ba44033ba30',
    messagingSenderId: '812253569425',
    projectId: 'uts-1123150059',
    authDomain: 'uts-1123150059.firebaseapp.com',
    storageBucket: 'uts-1123150059.firebasestorage.app',
    measurementId: 'G-MSSDV81N03',
  );
}
